---
- name: Guix cache server setup
  hosts: all
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=known_hosts'
  gather_facts: true
  tasks:
    - block:
        - name: Initialize secondary guix system account
          ansible.builtin.user:
            name: guix-dist
            system: true
            state: present
            home: /opt/guix-dist
            password_lock: true

        - name: Copy systemd service file
          ansible.builtin.copy:
            src: guix-publish.service
            dest: /etc/systemd/system/guix-publish.service

        - name: Setup systemd service
          ansible.builtin.systemd_service:
            daemon_reload: true
            enabled: true
            state: restarted
            masked: false
            name: guix-publish
      become: true

    - name: Get supported architectures
      ansible.builtin.shell: "uname -m"
      register: architecture

    - name: Save supported architectures
      delegate_to: localhost
      run_once: false
      vars:
        local_filename: "./{{ inventory_hostname }}_arch"
      copy:
        content: "{{ architecture.stdout }}"
        dest: "{{ local_filename }}"
